import org.junit.Test;

import static junit.framework.TestCase.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

public class DominikMatuszekPhoneBookTest {

    @Test
    public void adding_elements_with_hostile_intent(){
        PhoneBook a = new PhoneBook();
        a.add("asdad");
        a.add("3 2 1");
        a.add("helo helo 3 2 0");
        a.add("slyszales kiedys zart o falowanych blaszkach?");
        a.add("01111111");
        a.changeFormat(PhoneBook.NumberFormat.HYPHENED);
        a.add("111-111-111");
        a.add("111-111-11");
        a.add("111-1111-11");
        a.add("przychodzi matematyk do baru");
        a.add("atam0000000");
        a.add("zbiorpusty0");
        a.add("zbi-orp-ust");
        a.add("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");

        assertEquals("{\n  111-111-111\n}\n",a.toString());
    }
    
    @Test
    public void adding_book_that_exceeds_capacity_is_incorrect(){
        var a = new PhoneBook(1);
        var b = new PhoneBook();
        b.add("111111111");
        b.add("222222222");
        a.add(b);
        a.add("111111111");
        assertEquals(1,a.size());
    }

    @Test
    public void adding_phonebooks_to_full_phonebook_is_valid(){
        var a = new PhoneBook(0);
        var b = new PhoneBook();

        assertTrue(a.isFull());

        a.add(b).add(a);

        assertFalse(a.isEmpty());

        assertEquals("{\n" +
                "  {\n" +
                "  }\n" +
                "  {\n" +
                "    {\n" +
                "    }\n" +
                "  }\n" +
                "}\n",a.toString());
    }

    @Test
    public void bad_arguments_for_constructors_should_use_default(){
        var a = new PhoneBook(null,-5);
        assertEquals(a.capacity(),10);
        assertTrue(a.isEmpty());
        a.add("111111111");
        var b = new PhoneBook();
        b.add("111111111");
        assertTrue(a.equals(b));
    }

    @Test
    public void empty_set_is_subset_of_everything(){
        var a = new PhoneBook();
        var b = new PhoneBook();
        assertTrue(a.supersetOf(b));
        assertTrue(a.subsetOf(b));

        b.add("111111111");
        assertTrue(a.subsetOf(b));

        var c = new PhoneBook();
        c.add(b);
        assertTrue(a.subsetOf(c));
    }

    @Test
    public void shouldnt_be_equal_to_other_classes(){
        var a = new PhoneBook();
        assertFalse(a.equals(5));
        assertFalse(a.equals("bulbulator"));
        assertFalse(a.equals(null));
    }
    
    @Test
    public void test_nulls_basic(){
        PhoneBook a = new PhoneBook();
        a.add("");
        a.add((String) null);

        a.add("111111111");
        a.add("011111111");

        a.changeFormat(null);
        a.changeFormat(null);
        a.changeFormat(PhoneBook.NumberFormat.HYPHENED);
        a.add("22-22-22");
        a.toString(); //zeby wymusic ewaluacje
        a.changeFormat(null);
        a.toString();
        a.changeFormat(PhoneBook.NumberFormat.DIGITS);
        a.changeFormat(null);

        assertFalse(a.contains((String) null));
        assertFalse(a.contains((PhoneBook) null));
        assertFalse(a.contains(""));
        assertFalse(a.equals(null));
        assertFalse(a.subsetOf(null));
        assertFalse(a.supersetOf(null));
        assertFalse(a.elementOf(null));

        assertEquals("{\n" +
                "  111111111\n" +
                "}\n", a.toString());

    }

    @Test
    public void test_nulls_constructor(){
        var b = new PhoneBook(null,-42);
        assertEquals(b.capacity(),10);
        b.add("111-111-111");
        b.add("111111111");
        assertFalse(b.contains("111-111-111"));
        assertTrue(b.contains("111111111"));
    }

    @Test
    public void test_nulls_null_phonebook_doing_stuff(){
        var c = new PhoneBook(null);
        var d = (PhoneBook) null; //buhahahaha
        c.add(d);
        assertTrue(c.isEmpty());
        assertEquals(c.size(),0);
        c.add(d).add(d).add(d).add(d);

        assertTrue(c.isEmpty());
        assertFalse(c.supersetOf(d));
        assertFalse(c.subsetOf(d));
        assertFalse(c.elementOf(d));

        c.add("222222222");
        c.changeFormat(PhoneBook.NumberFormat.HYPHENED);
        c.add("222-222-222");
        c.changeFormat(null);
        c.changeFormat(PhoneBook.NumberFormat.DIGITS);
        assertEquals("{\n" +
                "  222222222\n" +
                "}\n",c.toString());
        assertFalse(c.contains(d));

        assertFalse(c.equals(d));
    }

    @Test
    public void test_nulls_null_string(){
        String nullstr = (String) null;
        var a = new PhoneBook();
        a.add(nullstr);
        a.changeFormat(PhoneBook.NumberFormat.HYPHENED);
        a.add(nullstr);

        a.add("111-111-111");
        a.add("222-222-222");

        assertFalse(a.contains(nullstr));
        assertFalse(a.equals(nullstr));
    }

    @Test
    public void empty_string_addition_and_contains(){
        String testString = "";
        var a = new PhoneBook();
        a.add(testString).add(testString).add(testString).add(testString).add(testString);
        a.changeFormat(PhoneBook.NumberFormat.HYPHENED);
        a.add(testString).add(testString).add(testString).add(testString).add(testString);

        assertTrue(a.isEmpty());
        assertFalse(a.contains(testString));
        a.changeFormat(PhoneBook.NumberFormat.DIGITS);
        assertFalse(a.contains(testString));
        assertFalse(a.equals(testString));

        a.add(a).add(a).add(a);
        assertFalse(a.isEmpty());
    }
    
    
    @Test
    public void big_to_string_test(){
        PhoneBook a = new PhoneBook(1000);
        PhoneBook b = new PhoneBook(1000);

        b.changeFormat(PhoneBook.NumberFormat.HYPHENED);
        b.changeFormat(PhoneBook.NumberFormat.HYPHENED);
        b.changeFormat(PhoneBook.NumberFormat.DIGITS);
        b.changeFormat(PhoneBook.NumberFormat.DIGITS);
        b.changeFormat(PhoneBook.NumberFormat.HYPHENED);

        b.add("111-111-111");

        b.changeFormat(PhoneBook.NumberFormat.DIGITS);
        b.changeFormat(PhoneBook.NumberFormat.HYPHENED);
        b.changeFormat(PhoneBook.NumberFormat.DIGITS);
        b.changeFormat(PhoneBook.NumberFormat.HYPHENED);
        b.changeFormat(PhoneBook.NumberFormat.DIGITS);
        b.changeFormat(PhoneBook.NumberFormat.HYPHENED);

        a.add(b);

        b.add("111-111-112");
        a.add(b);
        b.add("111-111-113");
        a.add(b);
        b.add("111-111-114");
        a.add(b);
        b.add("111-111-115");
        a.add(b);
        b.add("111-111-116");
        a.add(b);
        b.add("111-111-117");
        a.add(b);


        PhoneBook c = new PhoneBook(1000);
        c.add(a);
        c.add(b);

        a.add(c);
        c.add(a);

        assertEquals("{\n" +
                "  {\n" +
                "    {\n" +
                "      111111111\n" +
                "    }\n" +
                "    {\n" +
                "      111111111\n" +
                "      111111112\n" +
                "    }\n" +
                "    {\n" +
                "      111111111\n" +
                "      111111112\n" +
                "      111111113\n" +
                "    }\n" +
                "    {\n" +
                "      111111111\n" +
                "      111111112\n" +
                "      111111113\n" +
                "      111111114\n" +
                "    }\n" +
                "    {\n" +
                "      111111111\n" +
                "      111111112\n" +
                "      111111113\n" +
                "      111111114\n" +
                "      111111115\n" +
                "    }\n" +
                "    {\n" +
                "      111111111\n" +
                "      111111112\n" +
                "      111111113\n" +
                "      111111114\n" +
                "      111111115\n" +
                "      111111116\n" +
                "    }\n" +
                "    {\n" +
                "      111111111\n" +
                "      111111112\n" +
                "      111111113\n" +
                "      111111114\n" +
                "      111111115\n" +
                "      111111116\n" +
                "      111111117\n" +
                "    }\n" +
                "  }\n" +
                "  {\n" +
                "    111111111\n" +
                "    111111112\n" +
                "    111111113\n" +
                "    111111114\n" +
                "    111111115\n" +
                "    111111116\n" +
                "    111111117\n" +
                "  }\n" +
                "  {\n" +
                "    {\n" +
                "      111111111\n" +
                "    }\n" +
                "    {\n" +
                "      111111111\n" +
                "      111111112\n" +
                "    }\n" +
                "    {\n" +
                "      111111111\n" +
                "      111111112\n" +
                "      111111113\n" +
                "    }\n" +
                "    {\n" +
                "      111111111\n" +
                "      111111112\n" +
                "      111111113\n" +
                "      111111114\n" +
                "    }\n" +
                "    {\n" +
                "      111111111\n" +
                "      111111112\n" +
                "      111111113\n" +
                "      111111114\n" +
                "      111111115\n" +
                "    }\n" +
                "    {\n" +
                "      111111111\n" +
                "      111111112\n" +
                "      111111113\n" +
                "      111111114\n" +
                "      111111115\n" +
                "      111111116\n" +
                "    }\n" +
                "    {\n" +
                "      111111111\n" +
                "      111111112\n" +
                "      111111113\n" +
                "      111111114\n" +
                "      111111115\n" +
                "      111111116\n" +
                "      111111117\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "        {\n" +
                "          111111111\n" +
                "        }\n" +
                "        {\n" +
                "          111111111\n" +
                "          111111112\n" +
                "        }\n" +
                "        {\n" +
                "          111111111\n" +
                "          111111112\n" +
                "          111111113\n" +
                "        }\n" +
                "        {\n" +
                "          111111111\n" +
                "          111111112\n" +
                "          111111113\n" +
                "          111111114\n" +
                "        }\n" +
                "        {\n" +
                "          111111111\n" +
                "          111111112\n" +
                "          111111113\n" +
                "          111111114\n" +
                "          111111115\n" +
                "        }\n" +
                "        {\n" +
                "          111111111\n" +
                "          111111112\n" +
                "          111111113\n" +
                "          111111114\n" +
                "          111111115\n" +
                "          111111116\n" +
                "        }\n" +
                "        {\n" +
                "          111111111\n" +
                "          111111112\n" +
                "          111111113\n" +
                "          111111114\n" +
                "          111111115\n" +
                "          111111116\n" +
                "          111111117\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        111111111\n" +
                "        111111112\n" +
                "        111111113\n" +
                "        111111114\n" +
                "        111111115\n" +
                "        111111116\n" +
                "        111111117\n" +
                "      }\n" +
                "    }\n" +
                "  }\n" +
                "}\n", c.toString());
    }


    @Test
    public void adding_subbooks(){
        var a = new PhoneBook(0);

        a.add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a);
        a.add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a).add(a);

        assertEquals(0,a.size());
        assertFalse(a.isEmpty());

        assertEquals("{\n" +
                "  {\n" +
                "  }\n" +
                "  {\n" +
                "    {\n" +
                "    }\n" +
                "  }\n" +
                "  {\n" +
                "    {\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "    }\n" +
                "  }\n" +
                "  {\n" +
                "    {\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "  }\n" +
                "  {\n" +
                "    {\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "  }\n" +
                "  {\n" +
                "    {\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "  }\n" +
                "  {\n" +
                "    {\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "  }\n" +
                "  {\n" +
                "    {\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "  }\n" +
                "  {\n" +
                "    {\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "                {\n" +
                "                  {\n" +
                "                  }\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "  }\n" +
                "  {\n" +
                "    {\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "                {\n" +
                "                  {\n" +
                "                  }\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "    {\n" +
                "      {\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "                {\n" +
                "                  {\n" +
                "                  }\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "      {\n" +
                "        {\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "                {\n" +
                "                  {\n" +
                "                  }\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "        {\n" +
                "          {\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "                {\n" +
                "                  {\n" +
                "                  }\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "          {\n" +
                "            {\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "                {\n" +
                "                  {\n" +
                "                  }\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "            {\n" +
                "              {\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "                {\n" +
                "                  {\n" +
                "                  }\n" +
                "                }\n" +
                "              }\n" +
                "              {\n" +
                "                {\n" +
                "                }\n" +
                "                {\n" +
                "                  {\n" +
                "                  }\n" +
                "                }\n" +
                "                {\n" +
                "                  {\n" +
                "                  }\n" +
                "                  {\n" +
                "                    {\n" +
                "                    }\n" +
                "                  }\n" +
                "                }\n" +
                "              }\n" +
                "            }\n" +
                "          }\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "  }\n" +
                "}\n",a.toString());
    }

}
